### PR TITLE
Add functionality to load not only jar files but also class files in any subdirectories of libPath

### PR DESCRIPTION
**Pull request by jcp19**
From my understanding, the current version of the `WalaToSootIRConverter` expects the library paths to point to jar files:
https://github.com/MagpieBridge/IRConverter/blob/91b377dee74f865dee1b9387d3cd05fc33168dc2/src/main/java/magpiebridge/converter/WalaToSootIRConverter.java#L70
https://github.com/MagpieBridge/IRConverter/blob/91b377dee74f865dee1b9387d3cd05fc33168dc2/src/main/java/magpiebridge/converter/WalaToSootIRConverter.java#L100

However, it may be useful to load .class files instead of .jar files or even a combination of both. This PR aims at adding that extra bit of functionality. I created the method `buildLibPathScope`
to build a new AnalysisScope for the lib files. This method is called in the constructors for `WalaToSootIRConverter`.

I created a new test to check that both .class and .jar files are properly loaded (`test_loadClassAndJar` in the `WalaToSootIRConverterTest` class) and all tests run successfully. Please note that `test_loadClassAndJar` terminates unsuccessfully in the current version of `WalaToSootIRConverter`.

Let me know if you find anything wrong with this PR that I may have missed or if I ignored any project convention (e.g. naming, error-treatment, wtv) 😄 

PS: shouldn't we use `ClassLoaderReference.Extension` instead of `ClassLoaderreference.Primordial` to load library code? (https://github.com/wala/WALA/wiki/Analysis-Scope)

### CODE REVIEW

**Comment by linghuiluo** [comment]
@jcp19 hi, thanks for the PR. Your code looks good. I will test it.
Meanwhile, there is a new release of MagpieBridge with better logging, see this tutorial  https://github.com/MagpieBridge/MagpieBridge/wiki/Tutorial-4.-Set-up-logger-and-tracer

**Comment by jcp19** [comment]
Awesome! looking forward to play with it

**Comment by linghuiluo** [comment]
@jcp19 yeah, you are right. We could use the Extension loader for dependencies, though for the classs loading it doen't make any difference here.

**Review by linghuiluo — APPROVED** [review]

**Comment by linghuiluo** [comment]
@all-contributors please add @jcp19  for Code, Ideas

**Pull request merged**
